version: "3.5"

services:
    digitaldatasheets:
        image: kitt4sme/digitaldatasheets:latest
        hostname: digitaldatasheets
        container_name: digitaldatasheets
        environment:
            - REACT_APP_NAME="Digital Datasheets"
            - REACT_APP_RAMP_ENDPOINT=/component
            - REACT_APP_RAMP_PORT=3001
            - REACT_APP_RAMP_HOST=http://localhost
        expose:
            - "3000"
        ports:
            - 3000:3000
        networks:
            - default-dd

networks:
    default-dd:
        driver: bridge
        ipam:
            config:
                - subnet: 172.19.6.0/24
